# Site settings
title: Academi.as 
email:  comercial@ideem.com.br
description: "O sistema de gestão de academias mais completo do Brasil."
baseurl: ""
url: "http://academi.as"

# Build settings
markdown: kramdown
permalink: pretty
