# Site settings
title: Academi.as 
email: your-email@domain.com
description: "O sistema de gestão de academias mais completo do Brasil."
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
